openapi: 3.0.0
info:
  version: 1.0.0
  title: PlayKUround API docs
  description: PlayKUround의 API 문서입니다
  license:
    name: MIT
# 배포시 주소 바꿔주기
servers:
  - url: "http://localhost:8000"
  - url: "http://localhost:80"
paths:
  ########### user path ###########
  /api/user/:
    $ref: "./paths/user/userGet.yaml"
  /api/user/getName:
    $ref: "./paths/user/userGetName.yaml"
  /api/user/checkEmail:
    $ref: "./paths/user/userCheckEmail.yaml"
  /api/user/checkName:
    $ref: "./paths/user/userCheckName.yaml"
  /api/user/register:
    $ref: "./paths/user/userRegister.yaml"
  /api/user/login:
    $ref: "./paths/user/userLogin.yaml"
  /api/user/logout:
    $ref: "./paths/user/userLogout.yaml"
  /api/user/update:
    $ref: "./paths/user/userUpdate.yaml"

  ########### place path ###########
  /api/place/getByFilter:
    $ref: "./paths/place/placeGetByFilter.yaml"
  /api/place/getByName:
    $ref: "./paths/place/placeGetByName.yaml"
  /api/place/getByArr:
    $ref: "./paths/place/placeGetByArr.yaml"
  /api/place/getByOne:
    $ref: "./paths/place/placeGetByOne.yaml"
  /api/place/getByMap:
    $ref: "./paths/place/placeGetByMap.yaml"
  /api/place/create:
    $ref: "./paths/place/placeCreate.yaml"
  /api/place/rate:
    $ref: "./paths/place/placeRate.yaml"

  ########### post path ###########
  /api/post/getByLatest:
    $ref: "./paths/post/postGetByLatest.yaml"
  /api/post/getByPlace:
    $ref: "./paths/post/postGetByPlace.yaml"
  /api/post/like:
    $ref: "./paths/post/postLike.yaml"
  /api/post/create:
    $ref: "./paths/post/postCreate.yaml"

  ########### comment path ###########
  /api/comment/create:
    $ref: "./paths/comment/commentCreate.yaml"

  ########### hashtag path ###########
  /api/hashtag/get:
    $ref: "./paths/hashtag/hashtagGet.yaml"
  /api/hashtag/create:
    $ref: "./paths/hashtag/hashtagCreate.yaml"

components:
  parameters: null
  schemas:
    User:
      $ref: "./schemas/user.yaml"
    Place:
      $ref: "./schemas/place.yaml"
    Post:
      $ref: "./schemas/post.yaml"
    Menu:
      $ref: "./schemas/menu.yaml"
    Image:
      $ref: "./schemas/image.yaml"
    Hashtag:
      $ref: "./schemas/hashtag.yaml"
    Comment:
      $ref: "./schemas/comment.yaml"
  # responses:
  #   BadRequest:
  #     $ref: "./responses/badRequest.yaml"
  #   InternalServerError:
  #     $ref: "./responses/internalServerError.yaml"
